name: grahnumb_task
description: Internship task

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  resize: ^1.0.0
  cached_network_image: ^3.2.0
  http: ^0.13.4
  get: ^4.6.1
  flutter_html: ^2.2.1
  url_launcher: ^6.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
